package application_dockerimage

import (
	"context"
	"fmt"
	"sort"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/marconneves/coolify-sdk-go/application"
)

// envDTOsFromMap converts a types.Map (string -> string) into the slice
// expected by the bulk endpoint, sorted by key for stable request payloads.
func envDTOsFromMap(ctx context.Context, m types.Map) ([]application.EnvDTO, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return []application.EnvDTO{}, diags
	}

	raw := map[string]string{}
	diags.Append(m.ElementsAs(ctx, &raw, false)...)
	if diags.HasError() {
		return nil, diags
	}

	keys := make([]string, 0, len(raw))
	for k := range raw {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	out := make([]application.EnvDTO, 0, len(keys))
	for _, k := range keys {
		v := raw[k]
		out = append(out, application.EnvDTO{Key: k, Value: v})
	}
	return out, diags
}

// stringValueFromPtr returns a Terraform StringValue from a string pointer,
// returning a null value when the pointer is nil.
func stringValueFromPtr(s *string) types.String {
	if s == nil {
		return types.StringNull()
	}
	return types.StringValue(*s)
}

// mapFromTfMap extracts a Go map[string]string from a Terraform map attribute.
func mapFromTfMap(ctx context.Context, m types.Map) (map[string]string, diag.Diagnostics) {
	var diags diag.Diagnostics
	out := map[string]string{}
	if m.IsNull() || m.IsUnknown() {
		return out, diags
	}
	diags.Append(m.ElementsAs(ctx, &out, false)...)
	return out, diags
}

// syncEnvs reconciles environment variables with the application:
//   - bulk-upserts every key in the new map (creates or updates as needed)
//   - deletes keys that existed in the prior state but are no longer present
//
// Keys outside both maps (e.g. managed by coolify_application_env or
// auto-generated by Coolify) are left untouched.
func syncEnvs(ctx context.Context, r *ApplicationDockerImageResource, applicationUUID string, plan, state types.Map) diag.Diagnostics {
	var diags diag.Diagnostics

	planned, d := mapFromTfMap(ctx, plan)
	diags.Append(d...)
	if diags.HasError() {
		return diags
	}
	previous, d := mapFromTfMap(ctx, state)
	diags.Append(d...)
	if diags.HasError() {
		return diags
	}

	if len(planned) > 0 {
		envs, d := envDTOsFromMap(ctx, plan)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		if _, err := r.client.Application.UpdateEnvsBulk(ctx, applicationUUID, envs); err != nil {
			diags.AddError("Client Error", fmt.Sprintf("Unable to bulk update envs, got error: %s", err))
			return diags
		}
	}

	removed := []string{}
	for k := range previous {
		if _, kept := planned[k]; !kept {
			removed = append(removed, k)
		}
	}
	if len(removed) == 0 {
		return diags
	}

	sort.Strings(removed)
	current, err := r.client.Application.ListEnvs(ctx, applicationUUID)
	if err != nil {
		diags.AddError("Client Error", fmt.Sprintf("Unable to list envs while reconciling deletes: %s", err))
		return diags
	}
	byKey := map[string]application.EnvironmentVariable{}
	for _, e := range *current {
		byKey[e.Key] = e
	}
	for _, k := range removed {
		e, ok := byKey[k]
		if !ok {
			continue
		}
		if err := r.client.Application.DeleteEnv(ctx, applicationUUID, e.UUID); err != nil {
			diags.AddError("Client Error", fmt.Sprintf("Unable to delete env %s: %s", k, err))
			return diags
		}
	}

	return diags
}
